class Error1 < Exception {}
class Error2 < Exception {}

try {
    throw Error1("error message");
    print("Try");
} catch (Error1, Error2) {
    print("Catch"); # expect: Catch
} else {
    print("Else");
}
print("Done"); # expect: Done
