class Error1 < Exception {}
class Error2 < Exception {}

try {
    var a;
    throw Error1("error message");
} catch Error1 as e1 {
    print(a);  # expect runtime error: NameError: Undefined variable 'a'.
}