# Test throwing Exception that propagates to top level
fun throwError() {
    throw Exception("Uncaught error from function");
}

throwError();  # expect runtime error: Exception: Uncaught error from function
print("This should not print");